global using Microsoft.EntityFrameworkCore;
global using Portfolio.Data;
global using Portfolio.Data.Database;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
global using System;
global using System.ComponentModel.DataAnnotations;